name = "snowy-rain-84a5"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true
preview_urls = true

[[routes]]
pattern = "keyscodesandmodes.com/api/*"
zone_name = "keyscodesandmodes.com"

[[kv_namespaces]]
binding = "REVOKED_SESSIONS"
id = "158e3ba3ffb2474b97c7be753039bf9a"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "74334a688fd348d282eeba7e100c74b1"
